### ISSUE TITLE
TypeError: Error while loading rule '@typescript-eslint/no-empty-function': Cannot read properties of undefined

### ISSUE THREAD

**Issue by marekdedic** [sveltejs/eslint-plugin-svelte#923]
When running `pnpm run update`, I get the following error:

```
/home/user/eslint-plugin-svelte/node_modules/.pnpm/eslint@9.15.0/node_modules/eslint/lib/rules/no-empty-function.js:125
        const [{ allow }] = context.options;
                 ^

TypeError: Error while loading rule '@typescript-eslint/no-empty-function': Cannot read properties of undefined (reading 'allow')
Occurred while linting /home/user/eslint-plugin-svelte/packages/eslint-plugin-svelte/src/types-for-node.ts
    at Object.create (/home/user/eslint-plugin-svelte/node_modules/.pnpm/eslint@9.15.0/node_modules/eslint/lib/rules/no-empty-function.js:125:18)
    at create (/home/user/eslint-plugin-svelte/node_modules/.pnpm/@typescript-eslint+eslint-plugin@7.18.0_@typescript-eslint+parser@7.18.0_eslint@9.15.0_typesc_dmdtqn535btny6mjh3zmxsioty/node_modules/@typescript-eslint/eslint-plugin/src/rules/no-empty-function.ts:68:28)
    at Object.create (/home/user/eslint-plugin-svelte/node_modules/.pnpm/@typescript-eslint+utils@7.18.0_eslint@9.15.0_typescript@5.6.3/node_modules/@typescript-eslint/utils/src/eslint-utils/RuleCreator.ts:103:14)
    at createRuleListeners (/home/user/eslint-plugin-svelte/node_modules/.pnpm/eslint@9.15.0/node_modules/eslint/lib/linter/linter.js:944:21)
    at /home/user/eslint-plugin-svelte/node_modules/.pnpm/eslint@9.15.0/node_modules/eslint/lib/linter/linter.js:1082:84
    at Array.forEach (<anonymous>)
    at runRules (/home/user/eslint-plugin-svelte/node_modules/.pnpm/eslint@9.15.0/node_modules/eslint/lib/linter/linter.js:1013:34)
    at #flatVerifyWithoutProcessors (/home/user/eslint-plugin-svelte/node_modules/.pnpm/eslint@9.15.0/node_modules/eslint/lib/linter/linter.js:1911:31)
    at Linter._verifyWithFlatConfigArrayAndWithoutProcessors (/home/user/eslint-plugin-svelte/node_modules/.pnpm/eslint@9.15.0/node_modules/eslint/lib/linter/linter.js:1993:49)
    at Linter._verifyWithFlatConfigArray (/home/user/eslint-plugin-svelte/node_modules/.pnpm/eslint@9.15.0/node_modules/eslint/lib/linter/linter.js:2082:21)
```

**Comment by marekdedic** [comment]
I think this is caused by typescript-eslint/typescript-eslint#10338 and can be fixed either by upgrading typescript-eslint to 8.15 or downgrading eslint to 9.14.
